In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/hospital_readmissions.csv")

In [3]:
df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no

In [4]:
df.shape

(25000, 17)

In [5]:
df.columns

Index(['age', 'time_in_hospital', 'n_lab_procedures', 'n_procedures',
       'n_medications', 'n_outpatient', 'n_inpatient', 'n_emergency',
       'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'glucose_test',
       'A1Ctest', 'change', 'diabetes_med', 'readmitted'],
      dtype='object')

In [6]:
df.dtypes

age                  object
time_in_hospital      int64
n_lab_procedures      int64
n_procedures          int64
n_medications         int64
n_outpatient          int64
n_inpatient           int64
n_emergency           int64
medical_specialty    object
diag_1               object
diag_2               object
diag_3               object
glucose_test         object
A1Ctest              object
change               object
diabetes_med         object
readmitted           object
dtype: object

In [7]:
df.isnull().sum()

age                  0
time_in_hospital     0
n_lab_procedures     0
n_procedures         0
n_medications        0
n_outpatient         0
n_inpatient          0
n_emergency          0
medical_specialty    0
diag_1               0
diag_2               0
diag_3               0
glucose_test         0
A1Ctest              0
change               0
diabetes_med         0
readmitted           0
dtype: int64

In [8]:
df["readmitted"].value_counts()

readmitted
no     13246
yes    11754
Name: count, dtype: int64

# Hospital Readmission Analysis

## Project Objective

This project investigates factors associated with hospital readmission using patient and hospital data.

## Initial Hypotheses

1. I hypothesise that older patients may have a higher rate of hospital readmission.

2. I hypothesise that patients with longer hospital stays may have a higher rate of readmission.

3. I hypothesise that patients with a greater number of previous hospital encounters may have a higher rate of readmission.

# Data Cleaning

In [9]:
df.isnull().sum()

age                  0
time_in_hospital     0
n_lab_procedures     0
n_procedures         0
n_medications        0
n_outpatient         0
n_inpatient          0
n_emergency          0
medical_specialty    0
diag_1               0
diag_2               0
diag_3               0
glucose_test         0
A1Ctest              0
change               0
diabetes_med         0
readmitted           0
dtype: int64

In [10]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

Series([], dtype: int64)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["readmitted"].value_counts()

readmitted
no     13246
yes    11754
Name: count, dtype: int64

In [13]:
df["change"].value_counts()

change
no     13497
yes    11503
Name: count, dtype: int64

In [14]:
df["diabetes_med"].value_counts()

diabetes_med
yes    19228
no      5772
Name: count, dtype: int64

In [15]:
df["glucose_test"].value_counts()

glucose_test
no        23625
normal      689
high        686
Name: count, dtype: int64

In [16]:
df["A1Ctest"].value_counts()

A1Ctest
no        20938
high       2827
normal     1235
Name: count, dtype: int64

In [17]:
df["medical_specialty"].value_counts()

medical_specialty
Missing                   12382
InternalMedicine           3565
Other                      2664
Emergency/Trauma           1885
Family/GeneralPractice     1882
Cardiology                 1409
Surgery                    1213
Name: count, dtype: int64

In [18]:
df["medical_specialty"].value_counts(normalize=True) * 100

medical_specialty
Missing                   49.528
InternalMedicine          14.260
Other                     10.656
Emergency/Trauma           7.540
Family/GeneralPractice     7.528
Cardiology                 5.636
Surgery                    4.852
Name: proportion, dtype: float64

In [19]:
df.describe()

,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency
count,25000.00000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,4.45332,43.24076,1.352360,16.252400,0.366400,0.615960,0.186600
std,3.00147,19.81862,1.715179,8.060532,1.195478,1.177951,0.885873
min,1.00000,1.00000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,2.00000,31.00000,0.000000,11.000000,0.000000,0.000000,0.000000
50%,4.00000,44.00000,1.000000,15.000000,0.000000,0.000000,0.000000
75%,6.00000,57.00000,2.000000,20.000000,0.000000,1.000000,0.000000
max,14.00000,113.00000,6.000000,79.000000,33.000000,15.000000,64.000000

In [20]:
count_columns = [
    "time_in_hospital",
    "n_lab_procedures",
    "n_procedures",
    "n_medications",
    "n_outpatient",
    "n_inpatient",
    "n_emergency"
]

(df[count_columns] < 0).sum()

time_in_hospital    0
n_lab_procedures    0
n_procedures        0
n_medications       0
n_outpatient        0
n_inpatient         0
n_emergency         0
dtype: int64

In [21]:
df.select_dtypes(include="object").nunique()

age                  6
medical_specialty    7
diag_1               8
diag_2               8
diag_3               8
glucose_test         3
A1Ctest              3
change               2
diabetes_med         2
readmitted           2
dtype: int64

In [22]:
df_clean = df.copy()

In [23]:
df_clean.shape

(25000, 17)

## Data Cleaning Decisions

The dataset was checked for missing values, duplicate records, invalid categorical values, and impossible negative values.

- No null (`NaN`) values were identified.
- No duplicate rows were identified.
- Categorical variables contained expected values.
- No negative values were found in the count-based numerical variables.
- The `medical_specialty` column contains `"Missing"` for approximately 49.5% of records. These records were retained rather than removed because deleting them would remove a substantial proportion of the dataset.
- No rows were removed during cleaning.

In [24]:
df_clean.to_csv("data/hospital_readmissions_clean.csv", index=False)

In [25]:
import os

os.listdir("data")

['.DS_Store',
 'hospital_readmissions_clean.csv',
 '.ipynb_checkpoints',
 'hospital_readmissions.csv']